### ISSUE TITLE
op_response:92 probable soultion for you

### ISSUE THREAD

**Issue by ItchyNitchy** [nakagami/firebirdsql#180]
I've encountered op_response:92 error with Firebird 3.0.5.

Problem was that i have 2 users with identical username on server.

Just want to leave it there cuz i spend tons of time tinkering server configs and error message was not very helpful

**Comment by nakagami** [comment]
Please write down the detailed steps where the error occurs

**Comment by artyom-smirnov** [comment]
I used such auth config to reproduce on master branch:

```
AuthServer = Srp256,Srp,Legacy_Auth
UserManager = Srp, Legacy_UserManager
WireCrypt = Enabled
```
1. Create user in Srp:
```sql
create user someuser password 'test1' using plugin Srp;
```

2. Code to reproduce. Login with wrong password:

```go
conn, err := sql.Open("firebirdsql", "someuser:test2@localhost/employee")
err = conn.Ping()
if err != nil {
    panic(err)
}
```

```
panic: Error op_response:92

goroutine 1 [running]:
main.main()
        /workspace/go-firebirdsql/master/_examples/test.go:14 +0x5d
```

Also, if you will try to connect as not existing user you will see crash:

```go
conn, err := sql.Open("firebirdsql", "notexisting:test2@localhost/employee")
err = conn.Ping()
```

```
panic: runtime error: slice bounds out of range [:2] with capacity 0

goroutine 1 [running]:
github.com/nakagami/firebirdsql.(*wireProtocol)._parse_connect_response(0xc00012a240, {0xc0000261bb, 0x9}, {0xc0000261c5, 0x5}, 0xc0000387e0, 0xc00006a6a0, 0xc00006a660)
        /workspace/go-firebirdsql/master/wireprotocol.go:523 +0xb25
github.com/nakagami/firebirdsql.newFirebirdsqlConn(0xc00007a0a0)
        /workspace/go-firebirdsql/master/connection.go:150 +0x18b
github.com/nakagami/firebirdsql.(*firebirdsqlDriver).Open(0xc000031c78?, {0x57d4d8?, 0x780de7508548?})
        /workspace/go-firebirdsql/master/driver.go:39 +0x3a
database/sql.dsnConnector.Connect(...)
        /opt/go-1.23.1/src/database/sql/sql.go:801
database/sql.(*DB).conn(0xc00007ed00, {0x5bcb20, 0x769f00}, 0x1)
        /opt/go-1.23.1/src/database/sql/sql.go:1423 +0x87e
database/sql.(*DB).PingContext.func1(0xf0?)
        /opt/go-1.23.1/src/database/sql/sql.go:892 +0x3a
database/sql.(*DB).retry(0xc000031f10?, 0xc000031ee0)
        /opt/go-1.23.1/src/database/sql/sql.go:1568 +0x42
database/sql.(*DB).PingContext(0xc00007ed00, {0x5bcb20, 0x769f00})
        /opt/go-1.23.1/src/database/sql/sql.go:891 +0x77
database/sql.(*DB).Ping(...)
        /opt/go-1.23.1/src/database/sql/sql.go:909
main.main()
        /workspace/go-firebirdsql/master/_examples/test.go:12 +0x3f

```

**Comment by nakagami** [comment]
https://github.com/nakagami/firebirdsql/pull/181
